# This JCasC file is tailored for the rootless Podman Quadlet configuration (`../jenkins.container`) bundled with this repository
jenkins:
  systemMessage: "${systemMessage}"
  noUsageStatistics: true
  slaveAgentPort: -1 # Docker Plugin attaches directly to dynamic agent containers, thus agent port is not needed.
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
        - id: "${JENKINS_ADMIN_USER}"
          password: "${JENKINS_ADMIN_PASSWORD}"
          properties:
            - theme:
                theme: "darkSystem" # Requires plugin `dark-theme` - see `Dockerfile`

  authorizationStrategy: # IMPORTANT: This configuration assumes a single user instance. If this instance will have more than one user or the users are not fully trusted, this authorization strategy MUST BE REPLACED with something more secure.
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  disableRememberMe: false # Don't disable "Keep me signed in”

  crumbIssuer: "standard"
  mode: NORMAL
  numExecutors: 0 # No executors on built-in node
  quietPeriod: 0

  clouds:
    - docker:
        name: "podman"
        containerCap: 100 # Default is 100, adjust as needed
        dockerApi:
          dockerHost:
            uri: "${DOCKER_HOST}"
          connectTimeout: 30
        exposeDockerHost: false
        templates:
          - connector:
              attach:
                user: "jenkins"
            dockerTemplateBase:
              image: "${CONTAINER_REGISTRY_HOST}/lab/jenkins-agent:latest"
              pullCredentialsId: "git-creds" # Credential ID for git server credentials -- see gitcreds seed job (`jenkins/gitcreds.groovy`)
              environmentsString: |-
                TZ=${TZ}
              mountsString: |-
                type=volume,source=trivy-cache,destination=/home/jenkins/.cache/trivy
              securityOpts:
                - "no-new-privileges:true"
              capabilitiesToDrop:
                - "ALL"
              cpus: "4"
              memoryLimit: 8192
              memorySwap: 8192
            labelString: "podman"
            mode: EXCLUSIVE

  globalNodeProperties:
    - envVars:
        env: # Expose shared settings to pipelines
          - key: "CONTAINER_REGISTRY_HOST"
            value: "${CONTAINER_REGISTRY_HOST}"
          - key: "ALERT_EMAIL"
            value: "${ALERT_EMAIL}"

security:
  contentSecurityPolicy:
    enforce: true
  globalJobDslSecurityConfiguration:
    useScriptSecurity: true
  scriptApproval:
    forceSandbox: true

unclassified:
  location:
    url: "${JENKINS_URL}"
    adminAddress: "${SMTP_USERNAME}"

  bitwarden:
    cliExecutablePath: "/usr/local/bin/bw"
    serverUrl: "${BITWARDEN_SERVER_URL}"
    apiCredentialId: "bitwarden-api-key"
    masterPasswordCredentialId: "bitwarden-master-password"
    cacheDuration: 5
    fileCredentialSuffixes: ".env,.yaml"

  giteaServers:
    servers:
      - credentialsId: git-creds
        displayName: scm
        manageHooks: true
        serverUrl: ${GIT_SERVER_URL}

  globalLibraries:
    libraries:
      - defaultVersion: "main"
        name: "JenkinsPipelines"
        retriever:
          modernSCM:
            scm:
              gitSource:
                remote: ${GIT_SERVER_URL}/lab/JenkinsPipelines.git # Also on Github! https://github.com/mwdle/JenkinsPipelines
                traits:
                  - "gitBranchDiscovery"

  mailer:
    replyToAddress: "${systemMessage} <${SMTP_USERNAME}>"
    smtpHost: ${SMTP_HOST}
    smtpPort: ${SMTP_PORT}
    useSsl: true
    authentication:
      username: ${SMTP_USERNAME}
      password: ${SMTP_PASSWORD}

  buildDiscarders:
    configuredBuildDiscarders:
      - "jobBuildDiscarder"
      - simpleBuildDiscarder:
          discarder:
            logRotator:
              numToKeepStr: "100"
              daysToKeepStr: "1095"

  whitelist: # Generic Webhook Trigger
    enabled: true
    whitelistItems:
      - hmacAlgorithm: "HmacSHA256"
        host: "172.16.0.0/16"

jobs:
  - file: /var/jenkins_home/JCasC/gitcreds.groovy
  - file: /var/jenkins_home/JCasC/orgfolder.groovy
  - file: /var/jenkins_home/JCasC/multibranch.groovy
